name: Build Android APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Install Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build with Gradle
        run: gradle assembleDebug
        working-directory: ./HotspotManager   # 👈 important fix

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: HotspotManager/app/build/outputs/apk/debug/app-debug.apk
